name: biluca_financas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  collection: ^1.18.0
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.4.0
  flutter_colorpicker: ^1.1.0
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.3
  path: any
  http: ^1.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  logging: ^1.2.0
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  get_it: ^7.7.0
  file_picker: ^8.1.1
  fluttertoast: ^8.2.5
  csv: ^6.0.0
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0
  msix: ^3.16.8
  flutter_iconpicker: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/gen/predict_win/
    - assets/gen/predict_win/resources/

msix_config:
  display_name: Biluca Finanças
  publisher_display_name: bilucacom
  identity_name: bilucacom.bilucafinancas
  msix_version: 1.0.0.0
  logo_path: assets\logo.png