// Mocks generated by Mockito 5.4.4 from annotations
// in biluca_financas/test/accountability/bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:biluca_financas/accountability/models/entry.dart' as _i2;
import 'package:biluca_financas/accountability/models/entry_request.dart'
    as _i6;
import 'package:biluca_financas/accountability/models/identification.dart'
    as _i3;
import 'package:biluca_financas/accountability/repo.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccountabilityEntry_0 extends _i1.SmartFake
    implements _i2.AccountabilityEntry {
  _FakeAccountabilityEntry_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccountabilityIdentification_1 extends _i1.SmartFake
    implements _i3.AccountabilityIdentification {
  _FakeAccountabilityIdentification_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountabilityRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountabilityRepo extends _i1.Mock
    implements _i4.AccountabilityRepo {
  @override
  _i5.Future<List<_i2.AccountabilityEntry>> getEntries({
    int? limit = 10,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntries,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i2.AccountabilityEntry>>.value(
            <_i2.AccountabilityEntry>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.AccountabilityEntry>>.value(
                <_i2.AccountabilityEntry>[]),
      ) as _i5.Future<List<_i2.AccountabilityEntry>>);

  @override
  _i5.Future<_i2.AccountabilityEntry> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i5.Future<_i2.AccountabilityEntry>.value(
            _FakeAccountabilityEntry_0(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.AccountabilityEntry>.value(
            _FakeAccountabilityEntry_0(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.AccountabilityEntry>);

  @override
  _i5.Future<_i2.AccountabilityEntry> add(
          _i6.AccountabilityEntryRequest? req) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [req],
        ),
        returnValue: _i5.Future<_i2.AccountabilityEntry>.value(
            _FakeAccountabilityEntry_0(
          this,
          Invocation.method(
            #add,
            [req],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.AccountabilityEntry>.value(
            _FakeAccountabilityEntry_0(
          this,
          Invocation.method(
            #add,
            [req],
          ),
        )),
      ) as _i5.Future<_i2.AccountabilityEntry>);

  @override
  _i5.Future<void> delete(_i2.AccountabilityEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.AccountabilityEntry> update(_i2.AccountabilityEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [entry],
        ),
        returnValue: _i5.Future<_i2.AccountabilityEntry>.value(
            _FakeAccountabilityEntry_0(
          this,
          Invocation.method(
            #update,
            [entry],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.AccountabilityEntry>.value(
            _FakeAccountabilityEntry_0(
          this,
          Invocation.method(
            #update,
            [entry],
          ),
        )),
      ) as _i5.Future<_i2.AccountabilityEntry>);

  @override
  _i5.Future<List<_i3.AccountabilityIdentification>> getIdentifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdentifications,
          [],
        ),
        returnValue: _i5.Future<List<_i3.AccountabilityIdentification>>.value(
            <_i3.AccountabilityIdentification>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.AccountabilityIdentification>>.value(
                <_i3.AccountabilityIdentification>[]),
      ) as _i5.Future<List<_i3.AccountabilityIdentification>>);

  @override
  _i5.Future<String?> addOrGetIdentification(
          _i3.AccountabilityIdentification? identification) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrGetIdentification,
          [identification],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i3.AccountabilityIdentification?> getIdentification(
          String? identificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdentification,
          [identificationId],
        ),
        returnValue: _i5.Future<_i3.AccountabilityIdentification?>.value(),
        returnValueForMissingStub:
            _i5.Future<_i3.AccountabilityIdentification?>.value(),
      ) as _i5.Future<_i3.AccountabilityIdentification?>);

  @override
  _i5.Future<_i3.AccountabilityIdentification> addIdentification(
          _i3.AccountabilityIdentification? identification) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIdentification,
          [identification],
        ),
        returnValue: _i5.Future<_i3.AccountabilityIdentification>.value(
            _FakeAccountabilityIdentification_1(
          this,
          Invocation.method(
            #addIdentification,
            [identification],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AccountabilityIdentification>.value(
                _FakeAccountabilityIdentification_1(
          this,
          Invocation.method(
            #addIdentification,
            [identification],
          ),
        )),
      ) as _i5.Future<_i3.AccountabilityIdentification>);

  @override
  _i5.Future<void> updateIdentification(
          _i3.AccountabilityIdentification? updatedIdentification) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIdentification,
          [updatedIdentification],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteIdentification(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIdentification,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
